# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: iris_flow.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='iris_flow.proto',
  package='irisflow',
  syntax='proto3',
  serialized_pb=_b('\n\x0firis_flow.proto\x12\x08irisflow\"\x0f\n\rStatusRequest\"<\n\x0eStatusResponse\x12\r\n\x05state\x18\x01 \x01(\r\x12\x0b\n\x03\x66ps\x18\x02 \x01(\r\x12\x0e\n\x06sensor\x18\x03 \x01(\t\"J\n\x0cStreamConfig\x12\r\n\x05width\x18\x01 \x01(\r\x12\x0e\n\x06height\x18\x02 \x01(\r\x12\x0e\n\x06\x66ormat\x18\x03 \x01(\r\x12\x0b\n\x03\x66ps\x18\x04 \x01(\r\"\x0f\n\rStreamRequest\"0\n\x0eStreamResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\r\n\x05\x65rror\x18\x02 \x01(\t\"\x1d\n\x0c\x46rameRequest\x12\r\n\x05\x63ount\x18\x01 \x01(\r\"d\n\rFrameResponse\x12\x10\n\x08\x66rame_id\x18\x01 \x01(\r\x12\r\n\x05width\x18\x02 \x01(\r\x12\x0e\n\x06height\x18\x03 \x01(\r\x12\x0c\n\x04\x64\x61ta\x18\x04 \x01(\x0c\x12\x14\n\x0ctimestamp_ns\x18\x05 \x01(\x04\"X\n\tIspConfig\x12\x12\n\nbrightness\x18\x01 \x01(\x05\x12\x10\n\x08\x63ontrast\x18\x02 \x01(\x05\x12\x12\n\nsaturation\x18\x03 \x01(\x05\x12\x11\n\tsharpness\x18\x04 \x01(\x05\"\x0c\n\nIspRequest\"\x1e\n\x0bIspResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x0f\n\rHealthRequest\"1\n\x0eHealthResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\t2\xf9\x03\n\x08IrisFlow\x12>\n\tGetStatus\x12\x17.irisflow.StatusRequest\x1a\x18.irisflow.StatusResponse\x12?\n\x0bStartStream\x12\x16.irisflow.StreamConfig\x1a\x18.irisflow.StreamResponse\x12?\n\nStopStream\x12\x17.irisflow.StreamRequest\x1a\x18.irisflow.StreamResponse\x12;\n\x08GetFrame\x12\x16.irisflow.FrameRequest\x1a\x17.irisflow.FrameResponse\x12\x34\n\x06SetIsp\x12\x13.irisflow.IspConfig\x1a\x15.irisflow.IspResponse\x12\x33\n\x06GetIsp\x12\x14.irisflow.IspRequest\x1a\x13.irisflow.IspConfig\x12\x41\n\x0cStreamFrames\x12\x16.irisflow.FrameRequest\x1a\x17.irisflow.FrameResponse0\x01\x12@\n\x0bHealthCheck\x12\x17.irisflow.HealthRequest\x1a\x18.irisflow.HealthResponseb\x06proto3')
)




_STATUSREQUEST = _descriptor.Descriptor(
  name='StatusRequest',
  full_name='irisflow.StatusRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=44,
)


_STATUSRESPONSE = _descriptor.Descriptor(
  name='StatusResponse',
  full_name='irisflow.StatusResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='state', full_name='irisflow.StatusResponse.state', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fps', full_name='irisflow.StatusResponse.fps', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sensor', full_name='irisflow.StatusResponse.sensor', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=106,
)


_STREAMCONFIG = _descriptor.Descriptor(
  name='StreamConfig',
  full_name='irisflow.StreamConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='width', full_name='irisflow.StreamConfig.width', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='height', full_name='irisflow.StreamConfig.height', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='format', full_name='irisflow.StreamConfig.format', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fps', full_name='irisflow.StreamConfig.fps', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=108,
  serialized_end=182,
)


_STREAMREQUEST = _descriptor.Descriptor(
  name='StreamRequest',
  full_name='irisflow.StreamRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=184,
  serialized_end=199,
)


_STREAMRESPONSE = _descriptor.Descriptor(
  name='StreamResponse',
  full_name='irisflow.StreamResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='irisflow.StreamResponse.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error', full_name='irisflow.StreamResponse.error', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=201,
  serialized_end=249,
)


_FRAMEREQUEST = _descriptor.Descriptor(
  name='FrameRequest',
  full_name='irisflow.FrameRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='count', full_name='irisflow.FrameRequest.count', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=251,
  serialized_end=280,
)


_FRAMERESPONSE = _descriptor.Descriptor(
  name='FrameResponse',
  full_name='irisflow.FrameResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='frame_id', full_name='irisflow.FrameResponse.frame_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='width', full_name='irisflow.FrameResponse.width', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='height', full_name='irisflow.FrameResponse.height', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='irisflow.FrameResponse.data', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp_ns', full_name='irisflow.FrameResponse.timestamp_ns', index=4,
      number=5, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=282,
  serialized_end=382,
)


_ISPCONFIG = _descriptor.Descriptor(
  name='IspConfig',
  full_name='irisflow.IspConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='brightness', full_name='irisflow.IspConfig.brightness', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='contrast', full_name='irisflow.IspConfig.contrast', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='saturation', full_name='irisflow.IspConfig.saturation', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sharpness', full_name='irisflow.IspConfig.sharpness', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=384,
  serialized_end=472,
)


_ISPREQUEST = _descriptor.Descriptor(
  name='IspRequest',
  full_name='irisflow.IspRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=474,
  serialized_end=486,
)


_ISPRESPONSE = _descriptor.Descriptor(
  name='IspResponse',
  full_name='irisflow.IspResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='irisflow.IspResponse.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=488,
  serialized_end=518,
)


_HEALTHREQUEST = _descriptor.Descriptor(
  name='HealthRequest',
  full_name='irisflow.HealthRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=520,
  serialized_end=535,
)


_HEALTHRESPONSE = _descriptor.Descriptor(
  name='HealthResponse',
  full_name='irisflow.HealthResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='irisflow.HealthResponse.status', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='version', full_name='irisflow.HealthResponse.version', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=537,
  serialized_end=586,
)

DESCRIPTOR.message_types_by_name['StatusRequest'] = _STATUSREQUEST
DESCRIPTOR.message_types_by_name['StatusResponse'] = _STATUSRESPONSE
DESCRIPTOR.message_types_by_name['StreamConfig'] = _STREAMCONFIG
DESCRIPTOR.message_types_by_name['StreamRequest'] = _STREAMREQUEST
DESCRIPTOR.message_types_by_name['StreamResponse'] = _STREAMRESPONSE
DESCRIPTOR.message_types_by_name['FrameRequest'] = _FRAMEREQUEST
DESCRIPTOR.message_types_by_name['FrameResponse'] = _FRAMERESPONSE
DESCRIPTOR.message_types_by_name['IspConfig'] = _ISPCONFIG
DESCRIPTOR.message_types_by_name['IspRequest'] = _ISPREQUEST
DESCRIPTOR.message_types_by_name['IspResponse'] = _ISPRESPONSE
DESCRIPTOR.message_types_by_name['HealthRequest'] = _HEALTHREQUEST
DESCRIPTOR.message_types_by_name['HealthResponse'] = _HEALTHRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StatusRequest = _reflection.GeneratedProtocolMessageType('StatusRequest', (_message.Message,), dict(
  DESCRIPTOR = _STATUSREQUEST,
  __module__ = 'iris_flow_pb2'
  # @@protoc_insertion_point(class_scope:irisflow.StatusRequest)
  ))
_sym_db.RegisterMessage(StatusRequest)

StatusResponse = _reflection.GeneratedProtocolMessageType('StatusResponse', (_message.Message,), dict(
  DESCRIPTOR = _STATUSRESPONSE,
  __module__ = 'iris_flow_pb2'
  # @@protoc_insertion_point(class_scope:irisflow.StatusResponse)
  ))
_sym_db.RegisterMessage(StatusResponse)

StreamConfig = _reflection.GeneratedProtocolMessageType('StreamConfig', (_message.Message,), dict(
  DESCRIPTOR = _STREAMCONFIG,
  __module__ = 'iris_flow_pb2'
  # @@protoc_insertion_point(class_scope:irisflow.StreamConfig)
  ))
_sym_db.RegisterMessage(StreamConfig)

StreamRequest = _reflection.GeneratedProtocolMessageType('StreamRequest', (_message.Message,), dict(
  DESCRIPTOR = _STREAMREQUEST,
  __module__ = 'iris_flow_pb2'
  # @@protoc_insertion_point(class_scope:irisflow.StreamRequest)
  ))
_sym_db.RegisterMessage(StreamRequest)

StreamResponse = _reflection.GeneratedProtocolMessageType('StreamResponse', (_message.Message,), dict(
  DESCRIPTOR = _STREAMRESPONSE,
  __module__ = 'iris_flow_pb2'
  # @@protoc_insertion_point(class_scope:irisflow.StreamResponse)
  ))
_sym_db.RegisterMessage(StreamResponse)

FrameRequest = _reflection.GeneratedProtocolMessageType('FrameRequest', (_message.Message,), dict(
  DESCRIPTOR = _FRAMEREQUEST,
  __module__ = 'iris_flow_pb2'
  # @@protoc_insertion_point(class_scope:irisflow.FrameRequest)
  ))
_sym_db.RegisterMessage(FrameRequest)

FrameResponse = _reflection.GeneratedProtocolMessageType('FrameResponse', (_message.Message,), dict(
  DESCRIPTOR = _FRAMERESPONSE,
  __module__ = 'iris_flow_pb2'
  # @@protoc_insertion_point(class_scope:irisflow.FrameResponse)
  ))
_sym_db.RegisterMessage(FrameResponse)

IspConfig = _reflection.GeneratedProtocolMessageType('IspConfig', (_message.Message,), dict(
  DESCRIPTOR = _ISPCONFIG,
  __module__ = 'iris_flow_pb2'
  # @@protoc_insertion_point(class_scope:irisflow.IspConfig)
  ))
_sym_db.RegisterMessage(IspConfig)

IspRequest = _reflection.GeneratedProtocolMessageType('IspRequest', (_message.Message,), dict(
  DESCRIPTOR = _ISPREQUEST,
  __module__ = 'iris_flow_pb2'
  # @@protoc_insertion_point(class_scope:irisflow.IspRequest)
  ))
_sym_db.RegisterMessage(IspRequest)

IspResponse = _reflection.GeneratedProtocolMessageType('IspResponse', (_message.Message,), dict(
  DESCRIPTOR = _ISPRESPONSE,
  __module__ = 'iris_flow_pb2'
  # @@protoc_insertion_point(class_scope:irisflow.IspResponse)
  ))
_sym_db.RegisterMessage(IspResponse)

HealthRequest = _reflection.GeneratedProtocolMessageType('HealthRequest', (_message.Message,), dict(
  DESCRIPTOR = _HEALTHREQUEST,
  __module__ = 'iris_flow_pb2'
  # @@protoc_insertion_point(class_scope:irisflow.HealthRequest)
  ))
_sym_db.RegisterMessage(HealthRequest)

HealthResponse = _reflection.GeneratedProtocolMessageType('HealthResponse', (_message.Message,), dict(
  DESCRIPTOR = _HEALTHRESPONSE,
  __module__ = 'iris_flow_pb2'
  # @@protoc_insertion_point(class_scope:irisflow.HealthResponse)
  ))
_sym_db.RegisterMessage(HealthResponse)



_IRISFLOW = _descriptor.ServiceDescriptor(
  name='IrisFlow',
  full_name='irisflow.IrisFlow',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=589,
  serialized_end=1094,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetStatus',
    full_name='irisflow.IrisFlow.GetStatus',
    index=0,
    containing_service=None,
    input_type=_STATUSREQUEST,
    output_type=_STATUSRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='StartStream',
    full_name='irisflow.IrisFlow.StartStream',
    index=1,
    containing_service=None,
    input_type=_STREAMCONFIG,
    output_type=_STREAMRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='StopStream',
    full_name='irisflow.IrisFlow.StopStream',
    index=2,
    containing_service=None,
    input_type=_STREAMREQUEST,
    output_type=_STREAMRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetFrame',
    full_name='irisflow.IrisFlow.GetFrame',
    index=3,
    containing_service=None,
    input_type=_FRAMEREQUEST,
    output_type=_FRAMERESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SetIsp',
    full_name='irisflow.IrisFlow.SetIsp',
    index=4,
    containing_service=None,
    input_type=_ISPCONFIG,
    output_type=_ISPRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetIsp',
    full_name='irisflow.IrisFlow.GetIsp',
    index=5,
    containing_service=None,
    input_type=_ISPREQUEST,
    output_type=_ISPCONFIG,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='StreamFrames',
    full_name='irisflow.IrisFlow.StreamFrames',
    index=6,
    containing_service=None,
    input_type=_FRAMEREQUEST,
    output_type=_FRAMERESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='HealthCheck',
    full_name='irisflow.IrisFlow.HealthCheck',
    index=7,
    containing_service=None,
    input_type=_HEALTHREQUEST,
    output_type=_HEALTHRESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_IRISFLOW)

DESCRIPTOR.services_by_name['IrisFlow'] = _IRISFLOW

# @@protoc_insertion_point(module_scope)
