# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from src.client import iris_flow_pb2 as iris__flow__pb2


class IrisFlowStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetStatus = channel.unary_unary(
        '/irisflow.IrisFlow/GetStatus',
        request_serializer=iris__flow__pb2.StatusRequest.SerializeToString,
        response_deserializer=iris__flow__pb2.StatusResponse.FromString,
        )
    self.StartStream = channel.unary_unary(
        '/irisflow.IrisFlow/StartStream',
        request_serializer=iris__flow__pb2.StreamConfig.SerializeToString,
        response_deserializer=iris__flow__pb2.StreamResponse.FromString,
        )
    self.StopStream = channel.unary_unary(
        '/irisflow.IrisFlow/StopStream',
        request_serializer=iris__flow__pb2.StreamRequest.SerializeToString,
        response_deserializer=iris__flow__pb2.StreamResponse.FromString,
        )
    self.GetFrame = channel.unary_unary(
        '/irisflow.IrisFlow/GetFrame',
        request_serializer=iris__flow__pb2.FrameRequest.SerializeToString,
        response_deserializer=iris__flow__pb2.FrameResponse.FromString,
        )
    self.SetIsp = channel.unary_unary(
        '/irisflow.IrisFlow/SetIsp',
        request_serializer=iris__flow__pb2.IspConfig.SerializeToString,
        response_deserializer=iris__flow__pb2.IspResponse.FromString,
        )
    self.GetIsp = channel.unary_unary(
        '/irisflow.IrisFlow/GetIsp',
        request_serializer=iris__flow__pb2.IspRequest.SerializeToString,
        response_deserializer=iris__flow__pb2.IspConfig.FromString,
        )
    self.StreamFrames = channel.unary_stream(
        '/irisflow.IrisFlow/StreamFrames',
        request_serializer=iris__flow__pb2.FrameRequest.SerializeToString,
        response_deserializer=iris__flow__pb2.FrameResponse.FromString,
        )
    self.HealthCheck = channel.unary_unary(
        '/irisflow.IrisFlow/HealthCheck',
        request_serializer=iris__flow__pb2.HealthRequest.SerializeToString,
        response_deserializer=iris__flow__pb2.HealthResponse.FromString,
        )


class IrisFlowServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetStatus(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def StartStream(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def StopStream(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetFrame(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SetIsp(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetIsp(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def StreamFrames(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def HealthCheck(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_IrisFlowServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetStatus': grpc.unary_unary_rpc_method_handler(
          servicer.GetStatus,
          request_deserializer=iris__flow__pb2.StatusRequest.FromString,
          response_serializer=iris__flow__pb2.StatusResponse.SerializeToString,
      ),
      'StartStream': grpc.unary_unary_rpc_method_handler(
          servicer.StartStream,
          request_deserializer=iris__flow__pb2.StreamConfig.FromString,
          response_serializer=iris__flow__pb2.StreamResponse.SerializeToString,
      ),
      'StopStream': grpc.unary_unary_rpc_method_handler(
          servicer.StopStream,
          request_deserializer=iris__flow__pb2.StreamRequest.FromString,
          response_serializer=iris__flow__pb2.StreamResponse.SerializeToString,
      ),
      'GetFrame': grpc.unary_unary_rpc_method_handler(
          servicer.GetFrame,
          request_deserializer=iris__flow__pb2.FrameRequest.FromString,
          response_serializer=iris__flow__pb2.FrameResponse.SerializeToString,
      ),
      'SetIsp': grpc.unary_unary_rpc_method_handler(
          servicer.SetIsp,
          request_deserializer=iris__flow__pb2.IspConfig.FromString,
          response_serializer=iris__flow__pb2.IspResponse.SerializeToString,
      ),
      'GetIsp': grpc.unary_unary_rpc_method_handler(
          servicer.GetIsp,
          request_deserializer=iris__flow__pb2.IspRequest.FromString,
          response_serializer=iris__flow__pb2.IspConfig.SerializeToString,
      ),
      'StreamFrames': grpc.unary_stream_rpc_method_handler(
          servicer.StreamFrames,
          request_deserializer=iris__flow__pb2.FrameRequest.FromString,
          response_serializer=iris__flow__pb2.FrameResponse.SerializeToString,
      ),
      'HealthCheck': grpc.unary_unary_rpc_method_handler(
          servicer.HealthCheck,
          request_deserializer=iris__flow__pb2.HealthRequest.FromString,
          response_serializer=iris__flow__pb2.HealthResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'irisflow.IrisFlow', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
